RUN:
  run_id: 0
  type: 'conv_lstm'                                         # model_type chosen for the training.
  forecast_horizon: 15

  epochs: 15
  patience: 5
  lr_patience: None
  lr_start: 0.00001
  loss: mean_absolute_error
  beta_1: 0.9
  beta_2: 0.999

MLFLOW:
  tracking_uri: 'sqlite:///mlflow.db'
  experiment_name: 'Conv_lstm'
  note: "Same params, mean absolte error"

# Remember to modify this
PATHS:
  images: /media/maciej/Volume/data/001_nowcasting/standard_IR              # Raw images folder path
  sensor: /data/df_data_15_5.parquet.gzip                          # Weather station data folder path
  out_final: /data/df_final.parquet.gzip
  checkpoint: /model/                                                # path to the model weight folder

# Parameter dictionaries
PARAMS:
  batch_size: 32
  dim: (8, 128, 128, 1)
  channel_IMG: 1
  shuffle: False
  elevation_threshold: 20
  train_split: 0.7
  val_split: 0.2
  epsilon: 1e-3

MODEL:
  residual_layers: 2
  residual_filters: 32
  lstm_units: 32


test:
  day_1: '2024-06-01'
  day_2: '2024-06-02'
  day_3: '2024-06-03'
  day_4: '2024-06-04'
  day_5: '2024-06-05'