MODEL:
  run_id: 0
  type: 'scnn_15_5'                                         # model_type chosen for the training.
  forecast_horizon: 15
  sequence_horizon: 5                                     # time horizon.
  NO_IMAGES: 3
  EPSILON: 1e-3
  img_size: [128, 128, 3]                                       # image size.
  CHANNELS: 1                                                # image channels.
  elevation_threshold: 20
  split: 0.8

  epochs: 15
  patience: 5
  lr_patience: None
  lr_start: 0.00001
  loss: mean_absolute_error
  beta_1: 0.9
  beta_2: 0.999

MLFLOW:
  tracking_uri: 'sqlite:///mlflow.db'
  experiment_name: 'CNN_nowcasting_shifted_images'
  note: "Same params, mean absolte error"

# Remember to modify this
PATHS:
  input_folder: data\IR_images              # Raw images folder path
  output_folder: data\standard_IR            # Postprocessed images folder path
  weather_files: data\sensors                          # Weather station data folder path
  checkpoint: model                                                # path to the model weight folder

# Parameter dictionaries
PARAMS:
  train_params:
    batch_size: 64
    dim: [128, 128, 3]
    channel_IMG: 1
    shuffle: False
    iftest: False

  val_params:
    batch_size: 64
    dim: [128, 128, 3]
    channel_IMG: 1
    shuffle: False
    iftest: False

  test_params:
    batch_size: 1
    dim: [128, 128, 3]
    channel_IMG: 1
    shuffle: False
    iftest: False


test:
  day_1: '2024-06-01'
  day_2: '2024-06-02'
  day_3: '2024-06-03'
  day_4: '2024-06-04'
  day_5: '2024-06-05'